In [110]:
import numpy as np

In [111]:
stim0 = [np.zeros(1),np.zeros(8),np.zeros(16)]
stim1 = [np.array([1.0]),np.zeros(8),np.zeros(16)]
stim2 = [np.array([1.0]),np.full(8,1),np.zeros(16)]
stim3 = [np.zeros(1),np.full(8,1),np.zeros(16)]

In [118]:
beta = 0
gamma = 1
eta = -np.full(8,1/8.0)

In [119]:
def ganglion(stim, beta, gamma, eta):
    return(beta + stim[0].dot(gamma) + stim[1].dot(eta))

In [120]:
ganglion(stim0, beta, gamma, eta)

array([ 0.])

In [121]:
ganglion(stim1, beta, gamma, eta)

array([ 1.])

In [122]:
ganglion(stim2, beta, gamma, eta)

array([ 0.])

In [123]:
ganglion(stim3, beta, gamma, eta)

array([-1.])